server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: ticket-system

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  session:
    jdbc:
      initialize-schema: always

# JWT
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours

# Logging Configuration
logging:
  level:
    com.ticketsystem: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


